site_name: Islamic Resources
site_description: A collection of Islamic resources for learning and teaching
site_url: https://samayethali.github.io/islamic-resources

theme:
  name: material
  font:
    # text: "Noto Sans"
    # text: "Source Sans Pro"
    text: "PT Sans"
    # text: "Merriweather"
    # text: "Raleway"
  features:
    - navigation.tabs
    # - navigation.top
  icon:
    logo: fontawesome/solid/book-quran
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode

nav:
  - Home: index.md
  - Qur'ān:
      - Overview: quran/overview.md
  - Ḥadīth:
      - Overview: hadith/overview.md
  - Dhikr:
      - Overview: dhikr/overview.md
  - Duʿās:
      - Overview: duas/overview.md
  - Fiqh:
      - Overview: fiqh/overview.md

extra:
  generator: false

markdown_extensions:
  - attr_list
