site_name: Islamic Resources
site_description: A collection of Islamic resources for learning and teaching
site_url: https://samayethali.github.io/

theme:
  name: material
  font:
    # text: "Noto Sans"
    # text: "Source Sans Pro"
    text: "PT Sans"
    # text: "Merriweather"
    # text: "Raleway"
  features:
    # - navigation.tracking
    # - navigation.top
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    # - toc.integrate
    # - content.action.edit
    # - content.code.copy
    # - content.tooltips

  icon:
    logo: fontawesome/solid/book-quran
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode

nav:
  - Home: index.md
  - Qur'ān:
      - quran/index.md
  - Ḥadīth:
      - hadith/index.md
  - Dhikr:
      - dhikr/index.md
  - Duʿās:
      - duas/index.md
      - Anxiety: duas/anxiety.md
      # - Duʿās:
        # - Sayyid al-Istighfār: duas/sayyid-al-istighfar.md
  # - Fiqh:
  #     - Overview: fiqh/overview.md

extra:
  generator: false

markdown_extensions:
  - attr_list
